import type { Permission, Role } from './types';

export const roles: Role[] = [
  {
    id: '1',
    name: 'Citizen',
    description: 'Người dân - Quyền mặc định cho người dùng thông thường',
    userCount: 14500,
    isCustom: false,
  },
  {
    id: '2',
    name: 'Enterprise Admin',
    description: 'Quản lý doanh nghiệp - Toàn quyền quản lý doanh nghiệp',
    userCount: 48,
    isCustom: false,
  },
  {
    id: '3',
    name: 'Enterprise Staff',
    description: 'Nhân viên doanh nghiệp - Quyền hạn chế',
    userCount: 135,
    isCustom: false,
  },
  {
    id: '4',
    name: 'Collector',
    description: 'Nhân viên thu gom - Xử lý công việc thu gom',
    userCount: 420,
    isCustom: false,
  },
  {
    id: '5',
    name: 'System Admin',
    description: 'Quản trị viên hệ thống - Toàn quyền hệ thống',
    userCount: 12,
    isCustom: false,
  },
  {
    id: '6',
    name: 'Super Admin',
    description: 'Super Admin - Quyền cao nhất',
    userCount: 3,
    isCustom: false,
  },
];

export const permissions: Permission[] = [
  {
    id: '1',
    name: 'Tạo báo cáo rác',
    citizen: true,
    enterprise: false,
    collector: false,
    admin: true,
  },
  {
    id: '2',
    name: 'Xem báo cáo của mình',
    citizen: true,
    enterprise: true,
    collector: true,
    admin: true,
  },
  {
    id: '3',
    name: 'Xem tất cả báo cáo',
    citizen: false,
    enterprise: true,
    collector: false,
    admin: true,
  },
  {
    id: '4',
    name: 'Quản lý yêu cầu thu gom',
    citizen: false,
    enterprise: true,
    collector: false,
    admin: true,
  },
  {
    id: '5',
    name: 'Phân công công việc',
    citizen: false,
    enterprise: true,
    collector: false,
    admin: true,
  },
  {
    id: '6',
    name: 'Cập nhật trạng thái công việc',
    citizen: false,
    enterprise: false,
    collector: true,
    admin: true,
  },
  {
    id: '7',
    name: 'Quản lý nhân viên thu gom',
    citizen: false,
    enterprise: true,
    collector: false,
    admin: true,
  },
  {
    id: '8',
    name: 'Xem thống kê cá nhân',
    citizen: true,
    enterprise: true,
    collector: true,
    admin: true,
  },
  {
    id: '9',
    name: 'Tích điểm thưởng',
    citizen: true,
    enterprise: false,
    collector: false,
    admin: false,
  },
  {
    id: '10',
    name: 'Đổi điểm thưởng',
    citizen: true,
    enterprise: false,
    collector: false,
    admin: false,
  },
  {
    id: '11',
    name: 'Gửi phản hồi',
    citizen: true,
    enterprise: true,
    collector: true,
    admin: false,
  },
  {
    id: '12',
    name: 'Quản lý người dùng',
    citizen: false,
    enterprise: false,
    collector: false,
    admin: true,
  },
  {
    id: '13',
    name: 'Quản lý doanh nghiệp',
    citizen: false,
    enterprise: false,
    collector: false,
    admin: true,
  },
  {
    id: '14',
    name: 'Xử lý khiếu nại',
    citizen: false,
    enterprise: false,
    collector: false,
    admin: true,
  },
  {
    id: '15',
    name: 'Cài đặt hệ thống',
    citizen: false,
    enterprise: false,
    collector: false,
    admin: true,
  },
];
