import type { Report } from './types';

export const reports: Report[] = [
  {
    id: '1',
    reportId: '#R20240112-089',
    type: 'Rác nguy hại',
    weight: '50kg',
    location: 'Bệnh viện XYZ, Q1',
    status: 'urgent',
    time: '30 phút trước',
    priority: 'high',
  },
  {
    id: '2',
    reportId: '#R20240112-087',
    type: 'Rác tái chế',
    weight: '25kg',
    location: '123 Nguyễn Huệ, Q1',
    status: 'pending',
    time: '1 giờ trước',
    priority: 'medium',
  },
  {
    id: '3',
    reportId: '#R20240112-085',
    type: 'Rác hữu cơ',
    weight: '30kg',
    location: '456 Lê Lợi, Q3',
    status: 'assigned',
    time: '2 giờ trước',
    priority: 'medium',
  },
  {
    id: '4',
    reportId: '#R20240112-083',
    type: 'Rác tái chế',
    weight: '15kg',
    location: '789 Pasteur, Q3',
    status: 'in-progress',
    time: '3 giờ trước',
    priority: 'low',
  },
  {
    id: '5',
    reportId: '#R20240112-081',
    type: 'Rác hữu cơ',
    weight: '20kg',
    location: '234 Võ Văn Tần, Q1',
    status: 'completed',
    time: '4 giờ trước',
    priority: 'low',
  },
  {
    id: '6',
    reportId: '#R20240112-079',
    type: 'Rác nguy hại',
    weight: '10kg',
    location: '567 Hai Bà Trưng, Q1',
    status: 'rejected',
    time: '5 giờ trước',
    priority: 'medium',
  },
];
